image: 'ruby:latest'

before_script:
  - apt-get update && apt-get install -y git

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - bundle install
    - gem build eisiges-di-provider-rails.gemspec
  artifacts:
    paths:
      - eisiges-di-provider-rails-*.gem
    expire_in: 1 week

test:
  stage: test
  script:
    - bundle install
    - bundle exec rake test

deploy:
  stage: deploy
  script:
    - gem install geminabox
    - gem inabox --host 'http://gems.mccollum.enterprises' eisiges-di-provider-rails-*.gem
  only:
    - master

after_script:
  - echo "End CI"
